# Generated by Django 4.2 on 2024-08-08 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_attributes_questions_skills_special_services_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricings',
            old_name='attribute',
            new_name='attributes',
        ),
    ]
